import { normalizeMediaUrl } from '../lib/media';

// Derive variant URL from original. "/uploads/abc.jpg" -> "/uploads/abc.hero.webp"
// External, data: and blob: URLs pass through unchanged (no variants exist).
function variantUrl(src, variant) {
  if (!src) return '';
  if (/^(https?:|data:|blob:)/i.test(src)) return src;
  const dot = src.lastIndexOf('.');
  if (dot < 0) return src;
  const base = src.slice(0, dot);
  return `${base}.${variant}.webp`;
}

const MOBILE_BREAKPOINT = '(max-width: 768px)';

/**
 * Responsive image that picks the best variant generated by the backend's
 * image processor (sharp). Falls back to the original on missing variants
 * or unsupported browsers.
 *
 * Props:
 * - src         original upload URL ("/uploads/abc.jpg") or any URL
 * - kind        primary variant for desktop: 'hero' | 'card' | 'thumb' | 'mobile'
 * - alt         accessibility text
 * - eager       set loading=eager (default: lazy)
 * - style       inline styles for the <img>
 * - className   class for the <img>
 * - imgRef      ref forwarded to the <img>
 * - onError     img onError handler (e.g. for graceful fallback containers)
 */
export default function ResponsiveImage({
  src,
  kind = 'hero',
  alt = '',
  eager = false,
  style,
  className,
  imgRef,
  onError,
}) {
  const normalized = normalizeMediaUrl(src);
  if (!normalized) return null;

  // External / data / blob — no variants exist, render plain <img>
  const isExternal = /^(https?:|data:|blob:)/i.test(normalized);
  if (isExternal) {
    return (
      <img
        ref={imgRef}
        src={normalized}
        alt={alt}
        loading={eager ? 'eager' : 'lazy'}
        decoding="async"
        onError={onError}
        style={style}
        className={className}
      />
    );
  }

  const desktopSrc = variantUrl(normalized, kind);
  const mobileSrc = variantUrl(normalized, 'mobile');

  return (
    <picture>
      <source media={MOBILE_BREAKPOINT} srcSet={mobileSrc} type="image/webp" />
      <source srcSet={desktopSrc} type="image/webp" />
      <img
        ref={imgRef}
        src={normalized}
        alt={alt}
        loading={eager ? 'eager' : 'lazy'}
        decoding="async"
        onError={onError}
        style={style}
        className={className}
      />
    </picture>
  );
}
