import { useEffect, useRef } from 'react';
import { normalizeMediaUrl } from '../lib/media';

// Derive variant URL from original. "/uploads/abc.jpg" -> "/uploads/abc.hero.webp"
// External, data: and blob: URLs pass through unchanged (no variants exist).
function variantUrl(src, variant) {
  if (!src) return '';
  if (/^(https?:|data:|blob:)/i.test(src)) return src;
  const dot = src.lastIndexOf('.');
  if (dot < 0) return src;
  const base = src.slice(0, dot);
  return `${base}.${variant}.webp`;
}

/**
 * Responsive image that picks the best variant generated by the backend
 * image processor (sharp). Uses <img srcset> + sizes — no <picture> wrapper,
 * so style/className flow straight to the rendered <img> element (important
 * for absolute-positioned hero banners).
 *
 * Browser support: srcset is supported by every browser since 2016. For
 * pre-WebP browsers (extremely rare today) the onError handler falls back
 * to the original jpg/png.
 *
 * Props:
 *   src        original upload URL ("/uploads/abc.jpg") or any URL
 *   kind       desktop variant: 'hero' | 'card' | 'thumb' | 'mobile'
 *   alt        accessibility text
 *   eager      loading=eager (default: lazy)
 *   style      inline styles for the <img>
 *   className  class for the <img>
 *   imgRef     ref forwarded to the <img>
 *   onError    img onError handler (e.g. for graceful fallback containers)
 */
export default function ResponsiveImage({
  src,
  kind = 'hero',
  alt = '',
  eager = false,
  style,
  className,
  imgRef,
  onError,
}) {
  const fallbackRef = useRef(null);
  const ref = imgRef || fallbackRef;
  const triedFallback = useRef(false);

  // Reset fallback flag when src changes
  useEffect(() => {
    triedFallback.current = false;
  }, [src]);

  const normalized = normalizeMediaUrl(src);
  if (!normalized) return null;

  // External / data / blob — no variants exist, render plain <img>
  const isExternal = /^(https?:|data:|blob:)/i.test(normalized);
  if (isExternal) {
    return (
      <img
        ref={ref}
        src={normalized}
        alt={alt}
        loading={eager ? 'eager' : 'lazy'}
        decoding="async"
        onError={onError}
        style={style}
        className={className}
      />
    );
  }

  const desktopSrc = variantUrl(normalized, kind);
  const mobileSrc = variantUrl(normalized, 'mobile');

  const handleError = (e) => {
    // If a WebP variant fails (e.g. legacy upload not yet reprocessed),
    // fall back to the original JPG/PNG once.
    if (!triedFallback.current && e.currentTarget.src !== normalized) {
      triedFallback.current = true;
      e.currentTarget.srcset = '';
      e.currentTarget.src = normalized;
      return;
    }
    onError?.(e);
  };

  return (
    <img
      ref={ref}
      src={desktopSrc}
      srcSet={`${mobileSrc} 768w, ${desktopSrc} 1920w`}
      sizes="(max-width: 768px) 100vw, 1920px"
      alt={alt}
      loading={eager ? 'eager' : 'lazy'}
      decoding="async"
      onError={handleError}
      style={style}
      className={className}
    />
  );
}
